/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unsika.kalkulator;

/**
 *
 * @author farid
 */
public class Calculator1 extends javax.swing.JFrame {

    int num1;
    int num2;
    int hasil;
    String op;
    
    /**
     * Creates new form NewJFrame
     */
    public Calculator1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cText = new javax.swing.JTextField();
        cNum1 = new javax.swing.JButton();
        cNum2 = new javax.swing.JButton();
        cNum3 = new javax.swing.JButton();
        cNum4 = new javax.swing.JButton();
        cNum5 = new javax.swing.JButton();
        cNum6 = new javax.swing.JButton();
        cNum7 = new javax.swing.JButton();
        cNum8 = new javax.swing.JButton();
        cNum9 = new javax.swing.JButton();
        cDec = new javax.swing.JButton();
        cNum0 = new javax.swing.JButton();
        cClear = new javax.swing.JButton();
        cPlus = new javax.swing.JButton();
        cMin = new javax.swing.JButton();
        cMultiply = new javax.swing.JButton();
        cDivide = new javax.swing.JButton();
        cModulo = new javax.swing.JButton();
        cResult = new javax.swing.JButton();
        cB = new javax.swing.JButton();
        cE = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cNum1.setText("1");
        cNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNum1ActionPerformed(evt);
            }
        });

        cNum2.setText("2");
        cNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNum2ActionPerformed(evt);
            }
        });

        cNum3.setText("3");
        cNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNum3ActionPerformed(evt);
            }
        });

        cNum4.setText("4");
        cNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNum4ActionPerformed(evt);
            }
        });

        cNum5.setText("5");
        cNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNum5ActionPerformed(evt);
            }
        });

        cNum6.setText("6");
        cNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNum6ActionPerformed(evt);
            }
        });

        cNum7.setText("7");
        cNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNum7ActionPerformed(evt);
            }
        });

        cNum8.setText("8");
        cNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNum8ActionPerformed(evt);
            }
        });

        cNum9.setText("9");
        cNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNum9ActionPerformed(evt);
            }
        });

        cDec.setText(".");
        cDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDecActionPerformed(evt);
            }
        });

        cNum0.setText("0");
        cNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNum0ActionPerformed(evt);
            }
        });

        cClear.setText("C");
        cClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cClearActionPerformed(evt);
            }
        });

        cPlus.setText("+");
        cPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPlusActionPerformed(evt);
            }
        });

        cMin.setText("-");
        cMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMinActionPerformed(evt);
            }
        });

        cMultiply.setText("*");
        cMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMultiplyActionPerformed(evt);
            }
        });

        cDivide.setText("/");
        cDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDivideActionPerformed(evt);
            }
        });

        cModulo.setText("%");
        cModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cModuloActionPerformed(evt);
            }
        });

        cResult.setText("=");
        cResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cResultActionPerformed(evt);
            }
        });

        cB.setText("B");
        cB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBActionPerformed(evt);
            }
        });

        cE.setText("E");
        cE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cDec, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cClear, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cMin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cResult, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cB, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cE, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cText, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(cText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cNum1)
                    .addComponent(cNum2)
                    .addComponent(cNum3)
                    .addComponent(cPlus)
                    .addComponent(cMin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cNum4)
                    .addComponent(cNum5)
                    .addComponent(cNum6)
                    .addComponent(cMultiply)
                    .addComponent(cDivide))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cNum7)
                    .addComponent(cNum8)
                    .addComponent(cNum9)
                    .addComponent(cModulo)
                    .addComponent(cResult))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cDec)
                    .addComponent(cNum0)
                    .addComponent(cClear)
                    .addComponent(cB)
                    .addComponent(cE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNum1ActionPerformed
        // TODO add your handling code here:
        String EnterNum = cText.getText()+cNum1.getText();
        cText.setText(EnterNum);
    }//GEN-LAST:event_cNum1ActionPerformed

    private void cNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNum2ActionPerformed
        // TODO add your handling code here:
        String EnterNum = cText.getText()+cNum2.getText();
        cText.setText(EnterNum);
    }//GEN-LAST:event_cNum2ActionPerformed

    private void cNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNum3ActionPerformed
        // TODO add your handling code here:
        String EnterNum = cText.getText()+cNum3.getText();
        cText.setText(EnterNum);
    }//GEN-LAST:event_cNum3ActionPerformed

    private void cNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNum4ActionPerformed
        // TODO add your handling code here:
        String EnterNum = cText.getText()+cNum4.getText();
        cText.setText(EnterNum);
    }//GEN-LAST:event_cNum4ActionPerformed

    private void cNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNum6ActionPerformed
        // TODO add your handling code here:
        String EnterNum = cText.getText()+cNum6.getText();
        cText.setText(EnterNum);
    }//GEN-LAST:event_cNum6ActionPerformed

    private void cNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNum5ActionPerformed
        // TODO add your handling code here:
        String EnterNum = cText.getText()+cNum5.getText();
        cText.setText(EnterNum);
    }//GEN-LAST:event_cNum5ActionPerformed

    private void cNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNum8ActionPerformed
        // TODO add your handling code here:
        String EnterNum = cText.getText()+cNum8.getText();
        cText.setText(EnterNum);
    }//GEN-LAST:event_cNum8ActionPerformed

    private void cNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNum9ActionPerformed
        // TODO add your handling code here:
        String EnterNum = cText.getText()+cNum9.getText();
        cText.setText(EnterNum);
    }//GEN-LAST:event_cNum9ActionPerformed

    private void cNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNum7ActionPerformed
        // TODO add your handling code here:
        String EnterNum = cText.getText()+cNum7.getText();
        cText.setText(EnterNum);
    }//GEN-LAST:event_cNum7ActionPerformed

    private void cDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDecActionPerformed
        // TODO add your handling code here:
        String EnterNum = cText.getText()+cDec.getText();
        cText.setText(EnterNum);
    }//GEN-LAST:event_cDecActionPerformed

    private void cClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cClearActionPerformed
        // TODO add your handling code here:
        num2 = 0;
        cText.setText("");
    }//GEN-LAST:event_cClearActionPerformed

    private void cNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNum0ActionPerformed
        // TODO add your handling code here:
        String EnterNum = cText.getText()+cNum0.getText();
        cText.setText(EnterNum);
    }//GEN-LAST:event_cNum0ActionPerformed

    private void cPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPlusActionPerformed
        // TODO add your handling code here:
        num1 = Integer.parseInt(cText.getText());
        cText.setText("");
        op = "+";
    }//GEN-LAST:event_cPlusActionPerformed

    private void cMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMinActionPerformed
        // TODO add your handling code here:
        num1 = Integer.parseInt(cText.getText());
        cText.setText("");
        op = "-";
    }//GEN-LAST:event_cMinActionPerformed

    private void cMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMultiplyActionPerformed
        // TODO add your handling code here:
        num1 = Integer.parseInt(cText.getText());
        cText.setText("");
        op = "*";
    }//GEN-LAST:event_cMultiplyActionPerformed

    private void cDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDivideActionPerformed
        // TODO add your handling code here:
        num1 = Integer.parseInt(cText.getText());
        cText.setText("");
        op = "/";
    }//GEN-LAST:event_cDivideActionPerformed

    private void cModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cModuloActionPerformed
        // TODO add your handling code here:
        num1 = Integer.parseInt(cText.getText());
        cText.setText("");
        op = "%";
    }//GEN-LAST:event_cModuloActionPerformed

    private void cResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cResultActionPerformed
        // TODO add your handling code here:
        num2 = Integer.parseInt(cText.getText());
        
        if (op.equals("+"))
            hasil = num1 + num2;
        if (op.equals("-"))
            hasil = num1 - num2;
        if (op.equals("*"))
            hasil = num1 * num2;
        if (op.equals("/"))
            hasil = num1 / num2;
        if (op.equals("%"))
            hasil = num1 % num2;
        
        cText.setText(hasil + " ");
    }//GEN-LAST:event_cResultActionPerformed

    private void cBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBActionPerformed

    private void cEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cB;
    private javax.swing.JButton cClear;
    private javax.swing.JButton cDec;
    private javax.swing.JButton cDivide;
    private javax.swing.JButton cE;
    private javax.swing.JButton cMin;
    private javax.swing.JButton cModulo;
    private javax.swing.JButton cMultiply;
    private javax.swing.JButton cNum0;
    private javax.swing.JButton cNum1;
    private javax.swing.JButton cNum2;
    private javax.swing.JButton cNum3;
    private javax.swing.JButton cNum4;
    private javax.swing.JButton cNum5;
    private javax.swing.JButton cNum6;
    private javax.swing.JButton cNum7;
    private javax.swing.JButton cNum8;
    private javax.swing.JButton cNum9;
    private javax.swing.JButton cPlus;
    private javax.swing.JButton cResult;
    private javax.swing.JTextField cText;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
